[profile.default]
solc_version = '0.8.20'
auto_detect_solc = false
optimizer = true
ffi = true
optimizer_runs = 1_000
fuzz_runs = 1_000
remappings = [
  "forge-std=lib/forge-std/src/",
  "solmate=lib/solmate/src/",
]