name: ci

on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  fmt:
    name: Forge Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Format
        run: forge fmt --check src/NftChecker.sol test/NftChecker.t.sol

  tests:
    name: Forge Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run Tests
        run: FOUNDRY_PROFILE=ci forge test

  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes

      - name: Check gas snapshots
        run: forge snapshot --check

  scripts:
    strategy:
      fail-fast: true
    name: Run Unix Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        continue-on-error: true

      - name: Run scripts
        run: |
          for file in script/*; do
            forge script $file
          done
